# The URL the site will be built for
base_url = "https://es-romo.github.io/coco"

compile_sass = true

build_search_index = true

[markdown]
highlight_code = true

external_links_target_blank=true

[extra]
menu = [
    {url = "/projects", name = "/projects"},
    {url = "/now", name = "/now"},
]