# The URL the site will be built for
base_url = "https://es-romo.github.io/coco"

compile_sass = true

[markdown]
external_links_target_blank = true

[extra]
menu = [
    {url = "/projects", name = "/projects"},
    {url = "/now", name = "/now"}
]